name: Deployment TaskFly backend

  # This workflow uses actions that are not certified by GitHub.
  # They are provided by a third-party and are governed by
  # separate terms of service, privacy policy, and support
  # documentation.

#on:
#  push:
#    branches: [ "master", "dev","feature/ON4T-174_Backend_for_Tasks" ]
# Publish semver tags as releases.
#  pull_request:
#    branches: [ "master" ]
on: workflow_dispatch


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25
        with:
          cosign-release: 'v1.9.0'


      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_IMAGE_NAME }}:${{github.head_ref || github.ref_name}}-${{ github.sha }}

      - name: Deploy Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "zeitodobackend"
          publish-profile: ${{secrets.AZURE_WEB_APP_PUBLISH_PROFILE}}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_IMAGE_NAME }}:${{github.head_ref || github.ref_name}}-${{ github.sha }}
      - name: Configure App Environments
        uses: Azure/appservice-settings@v1
        with:
          app-name: 'zeitodobackend'
          app-settings-json: |
            [
                {
                    "name": "MONGO_URL",
                    "value": "${{ secrets.MONGO_URL }}",
                    "slotSetting": false
                },
                {
                    "name": "JWT_SECRET",
                    "value": "${{ secrets.JWT_SECRET }}",
                    "slotSetting": false
                },
                {
                    "name": "environment",
                    "value": "${{ secrets.MAIL_HOST }}",
                    "slotSetting": false
                }
            ]
